name: On Tag creation

on:
  push:
    tags:        
      - '*' 

jobs:
  build:
    name: Print Tag version
    runs-on: macos-latest
    steps:
    
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: YMLSreekanth/PackageB
          event-type: on_token_update
          client-payload: '{"tag": "${{ steps.vars.outputs.tag }}"}'
